"""create core rambutan schema

Revision ID: 153c50fcf7dc
Revises:
Create Date: 2026-09-20 18:15:20.397484

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "153c50fcf7dc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "garden",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("location_name", sa.String(length=160), nullable=True),
        sa.Column("area_m2", sa.Float(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "tree",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("garden_id", sa.Integer(), nullable=False),
        sa.Column("species", sa.String(length=80), nullable=False),
        sa.Column("variety", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["garden_id"],
            ["garden.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "observation_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tree_id", sa.Integer(), nullable=False),
        sa.Column("observation_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observer", sa.String(length=120), nullable=True),
        sa.Column("inspection_mode", sa.String(length=20), nullable=False),
        sa.Column("observation_quality", sa.String(length=32), nullable=True),
        sa.Column("general_condition", sa.String(length=80), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tree_id"],
            ["tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("observation_session", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_observation_session_tree_id"), ["tree_id"], unique=False
        )

    op.create_table(
        "field_prediction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("observation_id", sa.Integer(), nullable=False),
        sa.Column("field_key", sa.String(length=100), nullable=False),
        sa.Column("prediction", sa.String(length=255), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observation_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "photo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("observation_id", sa.Integer(), nullable=False),
        sa.Column("capture_type", sa.String(length=40), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("quality_status", sa.String(length=32), nullable=True),
        sa.Column("quality_reasons", sa.Text(), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observation_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "soil_observation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("observation_id", sa.Integer(), nullable=False),
        sa.Column("soil_visual_condition", sa.String(length=80), nullable=True),
        sa.Column("soil_moisture_visual", sa.String(length=40), nullable=True),
        sa.Column("standing_water", sa.Boolean(), nullable=False),
        sa.Column("leaf_wilt", sa.Boolean(), nullable=False),
        sa.Column("surface_dark", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observation_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("observation_id"),
    )
    op.create_table(
        "user_correction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prediction_id", sa.Integer(), nullable=False),
        sa.Column("ai_original_value", sa.String(length=255), nullable=False),
        sa.Column("user_final_value", sa.String(length=255), nullable=False),
        sa.Column("was_corrected", sa.Boolean(), nullable=False),
        sa.Column("correction_source", sa.String(length=40), nullable=False),
        sa.Column("correction_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["field_prediction.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_correction")
    op.drop_table("soil_observation")
    op.drop_table("photo")
    op.drop_table("field_prediction")
    with op.batch_alter_table("observation_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_observation_session_tree_id"))

    op.drop_table("observation_session")
    op.drop_table("tree")
    op.drop_table("user")
    op.drop_table("garden")
    # ### end Alembic commands ###
