"""add longitudinal analytics and model metadata

Revision ID: 958d06f21f28
Revises: 153c50fcf7dc
Create Date: 2026-09-20 19:39:45.287907

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "958d06f21f28"
down_revision = "153c50fcf7dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("task", sa.String(length=80), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("runtime", sa.String(length=80), nullable=True),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("metrics_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_id"),
    )
    op.create_table(
        "sensor_device",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_code", sa.String(length=80), nullable=False),
        sa.Column("sensor_type", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_code"),
    )
    op.create_table(
        "system_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "weather_observation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("garden_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rain_amount_mm", sa.Float(), nullable=True),
        sa.Column("rain_intensity", sa.String(length=40), nullable=True),
        sa.Column("sun_condition", sa.String(length=40), nullable=True),
        sa.Column("wind_condition", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["garden_id"],
            ["garden.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("weather_observation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_weather_observation_garden_id"), ["garden_id"], unique=False
        )

    op.create_table(
        "disease_observation",
        sa.Column("present", sa.Boolean(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("symptom_type", sa.String(length=80), nullable=True),
        sa.Column("severity", sa.String(length=40), nullable=True),
        sa.Column("affected_percent", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tree_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tree_id"],
            ["tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("disease_observation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_disease_observation_tree_id"), ["tree_id"], unique=False
        )

    op.create_table(
        "fertilizer_event",
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("product", sa.String(length=160), nullable=True),
        sa.Column("amount_g", sa.Float(), nullable=True),
        sa.Column("manure_kg", sa.Float(), nullable=True),
        sa.Column("application_method", sa.String(length=80), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tree_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tree_id"],
            ["tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fertilizer_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fertilizer_event_tree_id"), ["tree_id"], unique=False
        )

    op.create_table(
        "flowering_observation",
        sa.Column("present", sa.Boolean(), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=True),
        sa.Column("cluster_count", sa.Integer(), nullable=True),
        sa.Column("abundance", sa.String(length=40), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tree_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tree_id"],
            ["tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("flowering_observation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_flowering_observation_tree_id"), ["tree_id"], unique=False
        )

    op.create_table(
        "fruit_observation",
        sa.Column("present", sa.Boolean(), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=True),
        sa.Column("cluster_count", sa.Integer(), nullable=True),
        sa.Column("count_estimate", sa.Integer(), nullable=True),
        sa.Column("average_diameter_mm", sa.Float(), nullable=True),
        sa.Column("damage_percent", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tree_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tree_id"],
            ["tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fruit_observation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fruit_observation_tree_id"), ["tree_id"], unique=False
        )

    op.create_table(
        "growth_measurement",
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("stem_diameter_cm", sa.Float(), nullable=True),
        sa.Column("stem_circumference_cm", sa.Float(), nullable=True),
        sa.Column("canopy_width_cm", sa.Float(), nullable=True),
        sa.Column("measurement_method", sa.String(length=40), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tree_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tree_id"],
            ["tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("growth_measurement", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_growth_measurement_tree_id"), ["tree_id"], unique=False
        )

    op.create_table(
        "harvest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tree_id", sa.Integer(), nullable=False),
        sa.Column("harvest_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fruit_count", sa.Integer(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("marketable_fruit_count", sa.Integer(), nullable=True),
        sa.Column("quality_grade", sa.String(length=40), nullable=True),
        sa.Column("revenue", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tree_id"],
            ["tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("harvest", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_harvest_tree_id"), ["tree_id"], unique=False
        )

    op.create_table(
        "pest_observation",
        sa.Column("present", sa.Boolean(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("severity", sa.String(length=40), nullable=True),
        sa.Column("affected_percent", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tree_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tree_id"],
            ["tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pest_observation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pest_observation_tree_id"), ["tree_id"], unique=False
        )

    op.create_table(
        "pruning_event",
        sa.Column("pruning_type", sa.String(length=80), nullable=True),
        sa.Column("branch_removed_count", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=160), nullable=True),
        sa.Column("wound_condition", sa.String(length=80), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tree_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tree_id"],
            ["tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pruning_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pruning_event_tree_id"), ["tree_id"], unique=False
        )

    op.create_table(
        "sensor_reading",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sensor_id", sa.Integer(), nullable=False),
        sa.Column("tree_id", sa.Integer(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metric", sa.String(length=80), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensor_device.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tree_id"],
            ["tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sensor_reading", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sensor_reading_sensor_id"), ["sensor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sensor_reading_tree_id"), ["tree_id"], unique=False
        )

    op.create_table(
        "watering_event",
        sa.Column("liters", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=80), nullable=True),
        sa.Column("duration_min", sa.Float(), nullable=True),
        sa.Column("reason", sa.String(length=160), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tree_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tree_id"],
            ["tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("watering_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_watering_event_tree_id"), ["tree_id"], unique=False
        )

    op.create_table(
        "weed_observation",
        sa.Column("level", sa.String(length=40), nullable=True),
        sa.Column("coverage_percent", sa.Float(), nullable=True),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("removed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tree_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tree_id"],
            ["tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("weed_observation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_weed_observation_tree_id"), ["tree_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("weed_observation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_weed_observation_tree_id"))

    op.drop_table("weed_observation")
    with op.batch_alter_table("watering_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watering_event_tree_id"))

    op.drop_table("watering_event")
    with op.batch_alter_table("sensor_reading", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sensor_reading_tree_id"))
        batch_op.drop_index(batch_op.f("ix_sensor_reading_sensor_id"))

    op.drop_table("sensor_reading")
    with op.batch_alter_table("pruning_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pruning_event_tree_id"))

    op.drop_table("pruning_event")
    with op.batch_alter_table("pest_observation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pest_observation_tree_id"))

    op.drop_table("pest_observation")
    with op.batch_alter_table("harvest", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_harvest_tree_id"))

    op.drop_table("harvest")
    with op.batch_alter_table("growth_measurement", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_growth_measurement_tree_id"))

    op.drop_table("growth_measurement")
    with op.batch_alter_table("fruit_observation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fruit_observation_tree_id"))

    op.drop_table("fruit_observation")
    with op.batch_alter_table("flowering_observation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_flowering_observation_tree_id"))

    op.drop_table("flowering_observation")
    with op.batch_alter_table("fertilizer_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fertilizer_event_tree_id"))

    op.drop_table("fertilizer_event")
    with op.batch_alter_table("disease_observation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_disease_observation_tree_id"))

    op.drop_table("disease_observation")
    with op.batch_alter_table("weather_observation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_weather_observation_garden_id"))

    op.drop_table("weather_observation")
    op.drop_table("system_log")
    op.drop_table("sensor_device")
    op.drop_table("model_metadata")
    # ### end Alembic commands ###
